# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Client
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += _CRT_SECURE_NO_WARNINGS
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
QT += widgets
include(Client.pri)
